apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false

  artifacts:
    - image: hfcdevops/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**./*.ts'
            dest: .
    - image: hfcdevops/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: hfcdevops/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**./*.ts'
            dest: .
    - image: hfcdevops/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**./*.ts'
            dest: .
    - image: hfcdevops/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: /src/**/*.ts'
            dest: .
    - image: hfcdevops/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: /src/**/*.ts'
            dest: .
